### ISSUE TITLE
Include Post Assets in Source

### ISSUE THREAD

**Issue by davidwesst** [westerndevs/western-devs-website#206]
Goal is to include images and other assets along with the post itself.

## Possible Hexo-based Solutions
- [Global Asset Folder](https://hexo.io/docs/asset-folders.html#Global-Asset-Folder)
- [Post Asset Folder](https://hexo.io/docs/asset-folders.html#Post-Asset-Folder)

## Tasks
* [ ] Setup a "standard" for how we let people add images
* [ ] Crawl current site and download all images, and update all posts with new local images
* [ ] Set build to fail if authors don't put images in correct places
* [ ] Set build to fail if images referenced in post are not found

**Comment by davidwesst** [comment]
I think both of these cause problems. More specifically:

* Global Folders
   * (PRO) Let's us use normal markdown syntax for images
   * (CON) Will get cluttered if we just dump images in there
* Post Asset Folders
   * (PRO) Images will be organized by post
   * (CON) Post files themselves are NOT in the folder, so the adding images experience be annoying.

**Comment by kbaley** [comment]
With Global Folders, can we subdivide them by year? E.g. /source/images/2018.

I watched the video on post asset folders and it doesn't seem too difficult. The `{% asset_img %}` syntax looks straightforward and there are other options for referencing them via `asset_link` and `asset_path`.

I'm not keen on having a set of folders alongside the posts though. The _posts folder is already a pretty healthy size. Not really a deal breaker though.

**Comment by kbaley** [comment]
From what I can tell, the standard ![]() syntax should still work with post asset folders. You may still have to update image paths though.

**Comment by davidwesst** [comment]
It works, as long as you're only using the post images on the post page. If we started using post images on other pages, let's say the home page, where we list the latest posts then it would cause issue.

Use case example is if we have featured images that we use when listing the posts.

Not an issue now, but something to consider.
